# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Track_Model.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(659, 433)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 10, 211, 44))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(32, 129, 255)\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("974868-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.BlockData = QtWidgets.QTableView(self.centralwidget)
        self.BlockData.setGeometry(QtCore.QRect(430, 60, 211, 301))
        self.BlockData.setObjectName("BlockData")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 50, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 220, 311, 141))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: white;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 5, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 0, 381, 211))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../BlueLine.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.Switchlightstaus = QtWidgets.QGroupBox(self.centralwidget)
        self.Switchlightstaus.setGeometry(QtCore.QRect(50, 130, 111, 81))
        self.Switchlightstaus.setObjectName("Switchlightstaus")
        self.pushButton.raise_()
        self.BlockData.raise_()
        self.label.raise_()
        self.groupBox.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 659, 22))
        self.menubar.setObjectName("menubar")
        self.menuTrack_Model = QtWidgets.QMenu(self.menubar)
        self.menuTrack_Model.setObjectName("menuTrack_Model")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpload_Track_Layout = QtWidgets.QAction(MainWindow)
        self.actionUpload_Track_Layout.setIcon(icon)
        self.actionUpload_Track_Layout.setObjectName("actionUpload_Track_Layout")
        self.menubar.addAction(self.menuTrack_Model.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Upload Track Layout"))
        self.groupBox.setTitle(_translate("MainWindow", "Failures"))
        self.label_4.setText(_translate("MainWindow", "Power Failure"))
        self.label_3.setText(_translate("MainWindow", "Track Circuit Failure"))
        self.label_2.setText(_translate("MainWindow", "Brake Rail"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.Switchlightstaus.setTitle(_translate("MainWindow", "Status"))
        self.menuTrack_Model.setTitle(_translate("MainWindow", "File"))
        self.actionUpload_Track_Layout.setText(_translate("MainWindow", "Upload Track Layout"))
