# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Track_Model.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os  # Add import statement for os module

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 368)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 10, 211, 31))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(32, 129, 255)\n"
"")
        icon = QtGui.QIcon()
        # Dynamically construct the path to the picture file relative to the script directory
        script_dir = os.path.dirname(os.path.abspath(__file__))
        picture_path = os.path.join(script_dir, "974868-200.png")
        icon.addPixmap(QtGui.QPixmap(picture_path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.BlockData = QtWidgets.QTableView(self.centralwidget)
        self.BlockData.setGeometry(QtCore.QRect(360, 60, 211, 241))
        self.BlockData.setObjectName("BlockData")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 40, 211, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 313, 194))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Switchlightstaus = QtWidgets.QGroupBox(self.widget)
        self.Switchlightstaus.setObjectName("Switchlightstaus")
        self.horizontalLayout.addWidget(self.Switchlightstaus)
        self.TrackLayout = QtWidgets.QGraphicsView(self.widget)
        self.TrackLayout.setObjectName("TrackLayout")
        self.horizontalLayout.addWidget(self.TrackLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 22))
        self.menubar.setObjectName("menubar")
        self.menuTrack_Model = QtWidgets.QMenu(self.menubar)
        self.menuTrack_Model.setObjectName("menuTrack_Model")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpload_Track_Layout = QtWidgets.QAction(MainWindow)
        self.actionUpload_Track_Layout.setIcon(icon)
        self.actionUpload_Track_Layout.setObjectName("actionUpload_Track_Layout")
        self.menubar.addAction(self.menuTrack_Model.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Upload Track Layout"))
        self.Switchlightstaus.setTitle(_translate("MainWindow", "Status"))
        self.menuTrack_Model.setTitle(_translate("MainWindow", "File"))
        self.actionUpload_Track_Layout.setText(_translate("MainWindow", "Upload Track Layout"))
