# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Track_Model.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TrackLayout = QtWidgets.QGraphicsView(self.centralwidget)
        self.TrackLayout.setGeometry(QtCore.QRect(20, 10, 261, 192))
        self.TrackLayout.setObjectName("TrackLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 10, 151, 21))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(32, 129, 255)\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/974868-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.BlockData = QtWidgets.QTableView(self.centralwidget)
        self.BlockData.setGeometry(QtCore.QRect(300, 40, 151, 241))
        self.BlockData.setObjectName("BlockData")
        self.Switchlightstaus = QtWidgets.QGroupBox(self.centralwidget)
        self.Switchlightstaus.setGeometry(QtCore.QRect(20, 120, 120, 80))
        self.Switchlightstaus.setObjectName("Switchlightstaus")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 261, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 22))
        self.menubar.setObjectName("menubar")
        self.menuTrack_Model = QtWidgets.QMenu(self.menubar)
        self.menuTrack_Model.setObjectName("menuTrack_Model")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTrack_Model.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Upload Track Layout"))
        self.Switchlightstaus.setTitle(_translate("MainWindow", "Status"))
        self.menuTrack_Model.setTitle(_translate("MainWindow", "File"))
